
button_press_global = {
    # 全局模式——“视图”菜单,所有操作模式当中都适用
        'action.global_view_selected':(
        "action.global_view_selected","框显所选","DOT",
    ),
        'action.global_view_all':(
        "action.global_view_all","框显全部","HOME",
    ),
        'action.global_localview':(
        "action.global_localview","局部视图","RADIOBUT_OFF",
    ),
        'view3d.localview_remove_from':(
        "view3d.localview_remove_from","从局部视图中移除","RADIOBUT_OFF",
    ),
        'action.global_object_as_camera':(
        "action.global_object_as_camera","设置活动物体为摄像机","OUTLINER_OB_CAMERA",
    ),
        'action.global_view_center_camera':(
        "action.global_view_center_camera","摄像机边界框","SELECT_SET",
    ),
        'action.global_call_view_viewpoint_menu':(
        "action.global_call_view_viewpoint_menu","视图","PRESET",
    ),
        'action.global_call_view_navigation_menu':(
        "action.global_call_view_navigation_menu","视图切换","PRESET",
    ),
        'action.global_zoom_border':(
        "action.global_zoom_border","框选放大","SELECT_SET",
    ),
        'action.zoom_camera_1_to_1':(
        "action.zoom_camera_1_to_1","1:1缩放摄像机视图","RADIOBUT_OFF",
    ),
        'action.global_fly':(
        "action.global_fly","飞行漫游模式","RADIOBUT_OFF",
    ),
        'action.global_walk':(
        "action.global_walk","行走漫步","RADIOBUT_OFF",
    ),
        'action.global_call_view_align_selected_menu':(
        "action.global_call_view_align_selected_menu","视图对齐活动项","PRESET",
    ),
        'action.global_call_view_align_menu':(
        "action.global_call_view_align_menu","对齐视图","PRESET",
    ),
        'action.global_view_all_center_true':(
        "action.global_view_all_center_true","游标居中并查看全部","CURSOR",
    ),
        'action.global_view_center_cursor':(
        "action.global_view_center_cursor","视图中心对齐游标","PIVOT_CURSOR",
    ),
        'action.global_camera_to_view':(
        "action.global_camera_to_view","活动摄像机对齐当前视角","OUTLINER_DATA_CAMERA",
    ),
        'action.global_camera_to_view_selected':(
        "action.global_camera_to_view_selected","活动摄像机对齐选中的物体","OUTLINER_OB_CAMERA",
    ),
        'action.global_lock_to_active_or_lock_clear':(
        "action.global_lock_to_active_or_lock_clear","锁定/解锁视图","CON_CAMERASOLVER",
    ),
        'action.global_call_view_regions_menu':(
        "action.global_call_view_regions_menu","视图框","PRESET",
    ),
        'action.global_clip_border':(
        "action.global_clip_border","裁剪框","CLIPUV_HLT",
    ),
        'action.global_render_border':(
        "action.global_render_border","开/关渲染框","RADIOBUT_OFF",
    ),
        'action.global_render_opengl':(
        "action.global_render_opengl","视图渲染图像","RENDER_STILL",
    ),
        'action.global_render_opengl_animation':(
        "action.global_render_opengl_animation","视图渲染动画","RENDER_ANIMATION",
    ),
        'action.global_render_opengl_keyframe':(
        "action.global_render_opengl_keyframe","视图渲染关键帧","RENDER_ANIMATION",
    ),
        'action.global_area_menu':(
        "action.global_area_menu","区域","PRESET",
    ),
        'screen.region_quadview':(
        "screen.region_quadview","四格视图","IMGDISPLAY",
    ),
        'screen.screen_full_area':(
        "screen.screen_full_area","区域最大化","MOD_LENGTH",
    ),
        'action.global_screen_screen_full_area':(
        "action.global_screen_screen_full_area","全屏模式","FULLSCREEN_ENTER",
    ),
        'action.meshedit_edit_show_face_orientation':(
        "action.meshedit_edit_show_face_orientation","面朝向","RADIOBUT_OFF",
    ),
    # “选择”菜单
        'action.global_select_all':(
        "action.global_select_all","全选","EVENT_A",
    ),
        'action.global_select_invert':(
        "action.global_select_invert","反选","RADIOBUT_OFF",
    ),
        'action.global_select_circle':(
        "action.global_select_circle","刷选","EVENT_C",
    ),
        'action.global_select_select_mirror':(
        "action.global_select_select_mirror","选择镜像","MOD_MIRROR",
    ),
        'action.global_select_select_random':(
        "action.global_select_select_random","随机选择","RADIOBUT_OFF",
    ),
        'action.call_global_select_more_or_less_menu':(
        "action.call_global_select_more_or_less_menu","加选/减选","FORCE_CHARGE",
    ),
        'action.global_select_select_parent_or_child':(
        "action.global_select_select_parent_or_child","父级/子级","ORIENTATION_PARENT",
    ),
        'action.select_select_grouped':(
        "action.select_select_grouped","按组选择","PRESET",
    ),
        'action.global_select_select_linked':(
        "action.global_select_select_linked","选择相连","LINK_BLEND",
    ),
        'action.object_select_pattern':(
        "action.object_select_pattern","按名称选择","RADIOBUT_OFF", 
    ),
        'action.global_select_select_similar':(
        "action.global_select_select_similar","选择相似","PRESET", 
    ),
        'action.global_selectt_select_ungrouped':(
        "action.global_selectt_select_ungrouped","未归组顶点","RADIOBUT_OFF", 
    ),
        'action.global_gpencil_select_select_first':(
        "action.global_gpencil_select_select_first","选择首点","RADIOBUT_OFF", 
    ),
        'action.global_gpencil_select_select_last':(
        "action.global_gpencil_select_select_last","选择末点","RADIOBUT_OFF", 
    ),
        'action.global_greasepencil_select_select_first':(
        "action.global_greasepencil_select_select_first","起始点","RADIOBUT_OFF", 
    ),
        'action.global_greasepencil_select_select_last':(
        "action.global_greasepencil_select_select_last","结束点","RADIOBUT_OFF", 
    ),
        'action.global_select_select_alternate':(
        "action.global_select_select_alternate","选择交替","RADIOBUT_OFF", 
    ),

    # 全局高频操作——“添加”菜单/“复制(Shift+D)”/“复制(Ctrl C)”/“粘贴(Ctrl V)”
        'action.global_add':(
        "action.global_add","添加","PRESET",
    ),
        'action.global_duplicate_move':(
        "action.global_duplicate_move","复制","DUPLICATE", 
    ),
        'action.global_copy':(
        "action.global_copy","复制","COPYDOWN",
    ),
        'action.global_paste':(
        "action.global_paste","粘贴","PASTEDOWN",
    ),
        'action.global_call_delete_menu':(
        "action.global_call_delete_menu","删除","EVENT_X",
    ),

    # 全局物体对象相对应的操作
        'action.global_transform':(
        "action.global_transform","变换","PRESET",
    ),    
        'action.global_transform_tosphere':(
        "action.global_transform_tosphere","球形化","SPHERE",
    ),  
        'action.global_transform_shear':(
        "action.global_transform_shear","切变","RADIOBUT_OFF",
    ), 
        'action.global_transform_bend':(
        "action.global_transform_bend","弯曲","RADIOBUT_OFF",
    ), 
        'action.global_transform_push_pull':(
        "action.global_transform_push_pull","推/拉","RADIOBUT_OFF",
    ), 
        'action.global_transform_translate_texturespace_true':(
        "action.global_transform_translate_texturespace_true","移动纹理空间","RADIOBUT_OFF",
    ), 
        'action.global_transform_resize_texturespace_true':(
        "action.global_transform_resize_texturespace_true","缩放纹理空间","RADIOBUT_OFF",
    ), 
        'action.global_transform_vertex_warp':(
        "action.global_transform_vertex_warp","弯绕","RADIOBUT_OFF",
    ), 
        'action.global_transform_vertex_random':(
        "action.global_transform_vertex_random","随机","RADIOBUT_OFF",
    ), 
        'action.global_transform_mirror':( 
        "action.global_transform_mirror","交互镜像","MOD_MIRROR",
    ),

    # 全局高频操作——“隐藏”/“隐藏未选项”/“显示隐藏项”
        'action.global_hide_view_set':(
        "action.global_hide_view_set","隐藏选中项","EVENT_H",
    ),
        'action.global_hide_view_set_unselected':(
        "action.global_hide_view_set_unselected","隐藏未选项","HIDE_ON",
    ),
        'action.global_hide_view_clear':(
        "action.global_hide_view_clear","显示隐藏项","HIDE_OFF",
    ),
        'action.global_hide_show_menu':(
        "action.global_hide_show_menu","显示/隐藏","PRESET",
    ),

    # 吸附
        'action.global_snap_menu':(
        "action.global_snap_menu","吸附","PRESET",
    ),    
        'action.global_selected_to_grid':(
        "action.global_selected_to_grid","选中项->栅格点","RADIOBUT_OFF",
    ), 
        'action.global_snap_selected_to_cursor_offset_false':(
        "action.global_snap_selected_to_cursor_offset_false","选中项->游标","RADIOBUT_OFF",
    ), 
        'action.global_snap_selected_to_cursor_offset_true':(
        "action.global_snap_selected_to_cursor_offset_true","选中项->游标(保持偏移)","RADIOBUT_OFF",
    ), 
        'action.global_snap_selected_to_active':(
        "action.global_snap_selected_to_active","选中项->活动项","RADIOBUT_OFF",
    ), 
        'action.global_snap_cursor_to_selected':(
        "action.global_snap_cursor_to_selected","游标->选中项","RADIOBUT_OFF",
    ), 
        'action.global_snap_cursor_to_center':(
        "action.global_snap_cursor_to_center","游标->世界原点","RADIOBUT_OFF",
    ), 
        'action.global_snap_cursor_to_grid':(
        "action.global_snap_cursor_to_grid","游标->栅格点","RADIOBUT_OFF",
    ), 
        'action.global_snap_cursor_to_active':(
        "action.global_snap_cursor_to_active","游标->活动项","RADIOBUT_OFF",
    ), 


        'action.global_apply':(
        "action.global_apply","应用","PRESET",
    ),
        'action.global_object_pose_clear':( 
        "action.global_object_pose_clear","清空","PRESET",
    ),
        'action.global_parent_menu':( 
        "action.global_parent_menu","父级","PRESET",
    ),
        'action.global_set_parent_menu':( 
        "action.global_set_parent_menu","设置父级目标","PRESET",
    ),
        'action.global_parent_clear_menu':( 
        "action.global_parent_clear_menu","清空父级","PRESET",
    ),

        # 切换坐标系
        'action.switch_orientation_menu':(
        "action.switch_orientation_menu","切换坐标系","PRESET",
    ),
        'action.orientation_to_global':(
        "action.orientation_to_global","全局","ORIENTATION_GLOBAL",
    ),
        'action.orientation_to_local':(
        "action.orientation_to_local","局部","ORIENTATION_LOCAL",
    ),
        'action.orientation_to_normal':(
        "action.orientation_to_normal","法向","ORIENTATION_NORMAL",
    ),
        'action.orientation_to_gimbal':(
        "action.orientation_to_gimbal","万向","ORIENTATION_GIMBAL",
    ),
        'action.orientation_to_view':(
        "action.orientation_to_view","视图","ORIENTATION_VIEW",
    ),
        'action.orientation_to_cursor':(
        "action.orientation_to_cursor","游标","ORIENTATION_CURSOR",
    ),
        'action.orientation_to_parent':(
        "action.orientation_to_parent","父级","ORIENTATION_PARENT",
    ),

    # 切换轴心点
        'action.switch_pivot_menu':(
        "action.switch_pivot_menu","切换轴心点","PRESET",
    ),
        'action.pivot_to_bounding_box_center':(
        "action.pivot_to_bounding_box_center","边界框中心","PIVOT_BOUNDBOX",
    ),
        'action.pivot_to_cursor':(
        "action.pivot_to_cursor","3D 游标","PIVOT_CURSOR",
    ),
        'action.pivot_to_individual_origins':(
        "action.pivot_to_individual_origins","各自的原点","PIVOT_INDIVIDUAL",
    ),
        'action.pivot_to_median_point':(
        "action.pivot_to_median_point","质心点","PIVOT_MEDIAN",
    ),
        'action.pivot_to_active_element':(
        "action.pivot_to_active_element","活动元素","PIVOT_ACTIVE",
    ),

    # 切换吸附
        'action.switch_snap_menu':(
        "action.switch_snap_menu","切换吸附","PRESET",
    ), 
        'action.switch_snap_toggle':(
        "action.switch_snap_toggle","开/关吸附","SNAP_ON",
    ),  
        'action.switch_snap_increment':(
        "action.switch_snap_increment","增量","SNAP_INCREMENT",
    ),    
        'action.switch_snap_vertex':(
        "action.switch_snap_vertex","顶点","SNAP_VERTEX",
    ),  
        'action.switch_snap_edge':(
        "action.switch_snap_edge","边","SNAP_EDGE",
    ),  
        'action.switch_snap_face':(
        "action.switch_snap_face","面投射","SNAP_FACE",
    ),
        'action.switch_snap_face_nearest':(
        "action.switch_snap_face_nearest","面最近","SNAP_FACE_NEAREST",
    ),
        'action.switch_snap_volume':(
        "action.switch_snap_volume","体积","SNAP_VOLUME",
    ),
        'action.switch_snap_edge_midpoint':(
        "action.switch_snap_edge_midpoint","边中点","SNAP_MIDPOINT",
    ),
        'action.switch_snap_edge_perpendicular':(
        "action.switch_snap_edge_perpendicular","垂直交线","SNAP_PERPENDICULAR",
    ),

    #切换衰减编辑
        'action.switch_proportional_menu':(
        "action.switch_proportional_menu","衰减编辑","PRESET",
    ),
        'action.switch_proportional_toggle':(
        "action.switch_proportional_toggle","开/关衰减编辑","PROP_ON",
    ),
        'action.switch_proportional_smooth':(
        "action.switch_proportional_smooth","平滑","SMOOTHCURVE",
    ),
        'action.switch_proportional_sphere':(
        "action.switch_proportional_sphere","球体","SPHERECURVE",
    ),
        'action.switch_proportional_root':(
        "action.switch_proportional_root","根凸","ROOTCURVE",
    ),
        'action.switch_proportional_inverse_square':(
        "action.switch_proportional_inverse_square","平方反比","INVERSESQUARECURVE",
    ),
        'action.switch_proportional_sharp':(
        "action.switch_proportional_sharp","锐利","SHARPCURVE",
    ),
        'action.switch_proportional_linear':(
        "action.switch_proportional_linear","线性","LINCURVE",
    ),
        'action.switch_proportional_constant':(
        "action.switch_proportional_constant","常值","NOCURVE",
    ),
        'action.switch_proportional_random':(
        "action.switch_proportional_random","随机","RNDCURVE",
    ),
    # 一些通用操作
        'action.transform_tosphere':(
        "action.transform_tosphere","球形化","RADIOBUT_OFF",
    ),
        'action.transform_shear':(
        "action.transform_shear","切变","RADIOBUT_OFF", 
    ),
        'action.transform_bend':(
        "action.transform_bend","弯曲","RADIOBUT_OFF", 
    ),

    # 物体模式——“物体”菜单
        'action.object_object_duplicate_move_linked':(
        "action.object_object_duplicate_move_linked","关联复制","DUPLICATE",
    ),
        'object.join':(
        "object.join","合并","RADIOBUT_OFF", "MESHOBJECT",
    ),
        'action.object_object_transform_transform_mode_align':(
        "action.object_object_transform_transform_mode_align","对齐到变换坐标系","RADIOBUT_OFF", 
    ),
        'object.randomize_transform':(
        "object.randomize_transform","随机变换","RADIOBUT_OFF", 
    ),
        'object.align':(
        "object.align","对齐物体","RADIOBUT_OFF",
    ),


        'SEPARATOR':("","","REMOVE"),
        'NO_BUTTON':(),
}
