button_press_gpencil_edit = {
    # "蜡笔"菜单
        'action.gpenciledit_transform_shrink_fatten':(
        "action.gpenciledit_transform_shrink_fatten","法向缩放","RADIOBUT_OFF",
    ),
        'action.gpenciledit_layer_active_menu':(
        "action.gpenciledit_layer_active_menu","活动层","PRESET",
    ),
        'action.gpenciledit_layer_add':(
        "action.gpenciledit_layer_add","新建层","ADD",
    ),
        'action.gpenciledit_animation_menu':(
        "action.gpenciledit_animation_menu","动画","PRESET",
    ),
        'action.gpenciledit_blank_frame_add_false':(
        "action.gpenciledit_blank_frame_add_false","在活动层播入空白帧","RADIOBUT_OFF",
    ),
        'action.gpenciledit_blank_frame_add_true':(
        "action.gpenciledit_blank_frame_add_true","在全部层插入空白帧","RADIOBUT_OFF",
    ),
        'action.gpenciledit_frame_duplicate_active':(
        "action.gpenciledit_frame_duplicate_active","复制活动层的活动帧","RADIOBUT_OFF",
    ),
        'action.gpenciledit_frame_duplicate_all':(
        "action.gpenciledit_frame_duplicate_all","复制全部层的活动帧","RADIOBUT_OFF",
    ),
        'action.gpenciledit_interpolate_sequence_modal':(
        "action.gpenciledit_interpolate_sequence_modal","插值顺序","RADIOBUT_OFF",
    ),    
        'action.call_gpenciledit_stroke_separate_menu':(
        "action.call_gpenciledit_stroke_separate_menu","分离","PRESET",
    ),
        'action.call_gpenciledit_stroke_split':(
        "action.call_gpenciledit_stroke_split","拆分","RADIOBUT_OFF",
    ),
        'action.gpenciledit_weight_gpencil':(
        "action.gpenciledit_weight_gpencil","权重","PRESET",
    ),
        'action.gpenciledit_cleanup_menu':(
        "action.gpenciledit_cleanup_menu","清理","PRESET",
    ),
        'action.gpenciledit_frame_clean_fill_active':(
        "action.gpenciledit_frame_clean_fill_active","清理边界笔画","RADIOBUT_OFF",
    ),
        'action.gpenciledit_frame_clean_fill_all':(
        "action.gpenciledit_frame_clean_fill_all","清理所有帧的边界笔画","RADIOBUT_OFF",
    ),
        'action.gpenciledit_frame_clean_loose':(
        "action.gpenciledit_frame_clean_loose","删除松散点","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_merge_by_distance':(
        "action.gpenciledit_stroke_merge_by_distance","按间距合并","RADIOBUT_OFF",
    ),
        'action.gpenciledit_frame_clean_duplicate':(
        "action.gpenciledit_frame_clean_duplicate","清理重复帧","RADIOBUT_OFF",
    ),
        'action.gpenciledit_recalc_geometry':(
        "action.gpenciledit_recalc_geometry","重新计算几何","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_reproject_menu':(
        "action.call_gpenciledit_reproject_menu","重投影笔画","PRESET",
    ),
    # “笔画”菜单
        'action.gpenciledit_stroke_subdivide':(
        "action.gpenciledit_stroke_subdivide","细分笔画","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_simplify_menu':(
        "action.call_gpenciledit_simplify_menu","简化笔画","PRESET",
    ),
        'action.call_gpenciledit_stroke_trim':(
        "action.call_gpenciledit_stroke_trim","修剪笔画","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_outline':(
        "action.gpenciledit_stroke_outline","笔画轮廓","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_stroke_join_menu':(
        "action.call_gpenciledit_stroke_join_menu","合并","PRESET",
    ),
        'action.gpenciledit_stroke_join_join':(
        "action.gpenciledit_stroke_join_join","合并笔画","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_join_joincopy':(
        "action.gpenciledit_stroke_join_joincopy","合并&复制笔画","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_move_to_layer_menu':(
        "action.call_gpenciledit_move_to_layer_menu","移动到层","PRESET",
    ),
        'action.call_gpenciledit_assign_material_menu':(
        "action.call_gpenciledit_assign_material_menu","指定材质","PRESET",
    ),
        'action.gpenciledit_set_active_material':(
        "action.gpenciledit_set_active_material","设为活动材质","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_stroke_arrange_menu':(
        "action.call_gpenciledit_stroke_arrange_menu","排列笔画","PRESET",
    ),
        'action.gpenciledit_stroke_arrange_top':(
        "action.gpenciledit_stroke_arrange_top","笔画移到最前","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_arrange_up':(
        "action.gpenciledit_stroke_arrange_up","笔画前移","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_arrange_down':(
        "action.gpenciledit_stroke_arrange_down","笔画后送","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_arrange_bottom':(
        "action.gpenciledit_stroke_arrange_bottom","笔画移到最后","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_cyclical_set':(
        "action.gpenciledit_stroke_cyclical_set","闭合笔画","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_cyclical_set_toggle':(
        "action.gpenciledit_stroke_cyclical_set_toggle","切换笔画循环","RADIOBUT_OFF",
    ),
        'action.call_gpenciledit_stroke_caps_set_menu':(
        "action.call_gpenciledit_stroke_caps_set_menu","切换封顶类型","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_flip':(
        "action.gpenciledit_stroke_flip","切换笔画方向","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_start_set':(
        "action.gpenciledit_stroke_start_set","设置笔画起始点","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_normalize_thickness':(
        "action.gpenciledit_stroke_normalize_thickness","规格化宽度","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_normalize_opacity':(
        "action.gpenciledit_stroke_normalize_opacity","规格化不透明度","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_normalize_opacity':(
        "action.gpenciledit_stroke_normalize_opacity","规格化不透明度","RADIOBUT_OFF",
    ),
        'action.gpenciledit_scale_thickness':(
        "action.gpenciledit_scale_thickness","缩放厚度","RADIOBUT_OFF",
    ),
    # "点"菜单
        'action.gpenciledit_extrude_move':(
        "action.gpenciledit_extrude_move","挤出","EVENT_E",
    ),
        'action.gpenciledit_stroke_smooth':(
        "action.gpenciledit_stroke_smooth","光滑","RADIOBUT_OFF",
    ),
        'action.gpenciledit_stroke_merge':(
        "action.gpenciledit_stroke_merge","合并点","RADIOBUT_OFF",
    ),
        'action.gpenciledit_gpencil_vertex_group_menu':(
        "action.gpenciledit_gpencil_vertex_group_menu","顶点组","PRESET",
    ),



}