
button_press_object = {
    # 物体模式——”选择“菜单
        'button.action_object_select_select_by_type_menu':(
        "button.action_object_select_select_by_type_menu","按类型全选","PRESET",
    ),
        'object.select_camera':(
        "object.select_camera","选择活动摄像机","OUTLINER_OB_CAMERA",
    ),
        'button.action_object_randomize_transform':(
        "button.action_object_randomize_transform","随机变换","RADIOBUT_OFF",
    ),
        'button.action_object_transform_object_align':(
        "button.action_object_transform_object_align","对齐物体","RADIOBUT_OFF",
    ),
    # 切换原点
        'button.action_call_object_origin_set_menu':(
        "button.action_call_object_origin_set_menu","设置原点","PRESET",
    ),
        'button.action_object_origin_set_geometry_origin':(
        "button.action_object_origin_set_geometry_origin","几何中心->原点","RADIOBUT_OFF",
    ),
        'button.action_object_origin_set_origin_geometry':(
        "button.action_object_origin_set_origin_geometry","原点->几何中心","RADIOBUT_OFF",
    ),
        'button.action_object_origin_set_origin_cursor':(
        "button.action_object_origin_set_origin_cursor","原点->3D 游标","RADIOBUT_OFF",
    ),
        'button.action_object_origin_set_origin_center_of_mass':(
        "button.action_object_origin_set_origin_center_of_mass","原点->质心(表面)","RADIOBUT_OFF",
    ),
        'button.action_object_origin_set_origin_center_of_volume':(
        "button.action_object_origin_set_origin_center_of_volume","原点->质心(体积)","RADIOBUT_OFF",
    ),
        'button.action_object_duplicate_move_linked':(
        "button.action_object_duplicate_move_linked","关联复制","DUPLICATE",
    ),
        'button.action_object_delete_global_true':(
        "button.action_object_delete_global_true","全局删除","RADIOBUT_OFF",
    ),
        'button.action_object_join':(
        "button.action_object_join","合并","RADIOBUT_OFF",
    ),
        'button.action_object_asset_menu':(
        "button.action_object_asset_menu","资源","PRESET",
    ),
        'button.action_object_asset_mark':(
        "button.action_object_asset_mark","标记为资产","RADIOBUT_OFF",
    ),
        'button.action_object_asset_clear_fake_user_false':(
        "button.action_object_asset_clear_fake_user_false","清理资产","RADIOBUT_OFF",
    ),
        'button.action_object_asset_clear_fake_user_true':(
        "button.action_object_asset_clear_fake_user_true","清理资产(设置伪用户)","RADIOBUT_OFF",
    ),
    # 集合
        'button.action_object_collection_menu':(
        "button.action_object_collection_menu","集合","PRESET",
    ),  
        'button.action_object_collection_create':(
        "button.action_object_collection_create","创建新集合","COLLECTION_NEW",
    ), 
        'button.action_object_move_to_collection':(
        "button.action_object_move_to_collection","移动到集合","RADIOBUT_OFF",
    ),  
        'button.action_object_link_to_collection':(
        "button.action_object_link_to_collection","关联至集合","RADIOBUT_OFF",
    ),  
        'button.action_object_collection_objects_remove':(
        "button.action_object_collection_objects_remove","从集合中移除","RADIOBUT_OFF",
    ),  
        'button.action_object_collection_objects_remove_all':(
        "button.action_object_collection_objects_remove_all","从所有集合中移除","RADIOBUT_OFF",
    ),  
        'button.action_object_collection_objects_add_active':(
        "button.action_object_collection_objects_add_active","将选中项添加到活动集合中","RADIOBUT_OFF",
    ),  
        'button.action_object_collection_objects_remove_active':(
        "button.action_object_collection_objects_remove_active","从活动集合中移除所选","RADIOBUT_OFF",
    ),  
}
